#!/usr/bin/env tsx
/**
 * Board Watch — Publish to Substack
 * Creates a *draft* post on Substack so you can review it before publishing.
 *
 * Uses Substack's internal API (no official public API exists).
 * Authenticates via the `substack.sid` session cookie.
 */

import "dotenv/config";
import { readdirSync, readFileSync, statSync } from "fs";
import { join, resolve } from "path";
import { Lexer, type Token, type Tokens } from "marked";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const PROJECT_ROOT = resolve(import.meta.dirname, "..");
const DRAFTS_DIR = join(PROJECT_ROOT, "data", "drafts");

const INTRO_PARAGRAPHS = [
  {
    type: "paragraph" as const,
    content: [
      {
        type: "text" as const,
        marks: [{ type: "bold" as const }],
        text: "Lebo Board Watch",
      },
      {
        type: "text" as const,
        text: " is an AI-generated weekly digest of Mt. Lebanon local government meetings — school board, municipal commission, and more — so busy residents can stay informed without sitting through hours of public meetings. New editions drop every Sunday morning.",
      },
    ],
  },
  { type: "horizontalRule" as const },
];

const FOOTER_NODES = [
  { type: "horizontalRule" as const },
  {
    type: "paragraph" as const,
    content: [
      { type: "text" as const, text: "Keep Lebo Watch running: " },
      {
        type: "text" as const,
        marks: [
          {
            type: "link" as const,
            attrs: { href: "https://buymeacoffee.com/leboboardwatcher" },
          },
        ],
        text: "Buy Me a Coffee",
      },
      { type: "text" as const, text: "." },
    ],
  },
  {
    type: "paragraph" as const,
    content: [
      {
        type: "text" as const,
        marks: [{ type: "italic" as const }],
        text: "This newsletter was generated by AI. If something's wrong, blame the robot.",
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Tiptap types
// ---------------------------------------------------------------------------

interface TiptapMark {
  type: string;
  attrs?: Record<string, unknown>;
}

interface TiptapTextNode {
  type: "text";
  text: string;
  marks?: TiptapMark[];
}

interface TiptapHardBreak {
  type: "hardBreak";
}

type TiptapInlineNode = TiptapTextNode | TiptapHardBreak;

interface TiptapBlockNode {
  type: string;
  attrs?: Record<string, unknown>;
  content?: (TiptapBlockNode | TiptapInlineNode)[];
}

interface TiptapDoc {
  type: "doc";
  attrs: { schemaVersion: string };
  content: TiptapBlockNode[];
}

// ---------------------------------------------------------------------------
// Markdown → Tiptap conversion
// ---------------------------------------------------------------------------

function inlineTokensToTiptap(tokens: Token[]): TiptapInlineNode[] {
  const nodes: TiptapInlineNode[] = [];

  for (const token of tokens) {
    switch (token.type) {
      case "text": {
        const t = token as Tokens.Text;
        // Text tokens can have nested tokens (e.g. from inline parsing)
        if (t.tokens && t.tokens.length > 0) {
          nodes.push(...inlineTokensToTiptap(t.tokens));
        } else {
          nodes.push({ type: "text", text: t.text });
        }
        break;
      }
      case "strong": {
        const t = token as Tokens.Strong;
        const children = t.tokens
          ? inlineTokensToTiptap(t.tokens)
          : [{ type: "text" as const, text: t.text }];
        for (const child of children) {
          if (child.type === "text") {
            const marks: TiptapMark[] = [
              { type: "bold" },
              ...(child.marks ?? []),
            ];
            nodes.push({ type: "text", text: child.text, marks });
          } else {
            nodes.push(child);
          }
        }
        break;
      }
      case "em": {
        const t = token as Tokens.Em;
        const children = t.tokens
          ? inlineTokensToTiptap(t.tokens)
          : [{ type: "text" as const, text: t.text }];
        for (const child of children) {
          if (child.type === "text") {
            const marks: TiptapMark[] = [
              { type: "italic" },
              ...(child.marks ?? []),
            ];
            nodes.push({ type: "text", text: child.text, marks });
          } else {
            nodes.push(child);
          }
        }
        break;
      }
      case "link": {
        const t = token as Tokens.Link;
        const linkText = t.tokens
          ? inlineTokensToTiptap(t.tokens)
          : [{ type: "text" as const, text: t.text }];
        for (const child of linkText) {
          if (child.type === "text") {
            const marks: TiptapMark[] = [
              { type: "link", attrs: { href: t.href } },
              ...(child.marks ?? []),
            ];
            nodes.push({ type: "text", text: child.text, marks });
          } else {
            nodes.push(child);
          }
        }
        break;
      }
      case "codespan": {
        const t = token as Tokens.Codespan;
        nodes.push({
          type: "text",
          text: t.text,
          marks: [{ type: "code" }],
        });
        break;
      }
      case "br": {
        nodes.push({ type: "hardBreak" });
        break;
      }
      case "escape": {
        const t = token as Tokens.Escape;
        nodes.push({ type: "text", text: t.text });
        break;
      }
      default: {
        // Fallback: render as plain text
        if ("text" in token && typeof token.text === "string") {
          nodes.push({ type: "text", text: token.text });
        }
        break;
      }
    }
  }

  return nodes;
}

function blockTokensToTiptap(tokens: Token[]): TiptapBlockNode[] {
  const nodes: TiptapBlockNode[] = [];

  for (const token of tokens) {
    switch (token.type) {
      case "heading": {
        const t = token as Tokens.Heading;
        const content = t.tokens ? inlineTokensToTiptap(t.tokens) : [];
        nodes.push({
          type: "heading",
          attrs: { level: t.depth },
          content: content.length > 0 ? content : undefined,
        });
        break;
      }
      case "paragraph": {
        const t = token as Tokens.Paragraph;
        const content = t.tokens ? inlineTokensToTiptap(t.tokens) : [];
        if (content.length > 0) {
          nodes.push({ type: "paragraph", content });
        }
        break;
      }
      case "hr": {
        nodes.push({ type: "horizontalRule" });
        break;
      }
      case "list": {
        const t = token as Tokens.List;
        const listType = t.ordered ? "orderedList" : "bulletList";
        const items: TiptapBlockNode[] = t.items.map((item) => {
          const itemContent = item.tokens
            ? blockTokensToTiptap(item.tokens)
            : [];
          return {
            type: "listItem",
            content:
              itemContent.length > 0
                ? itemContent
                : [{ type: "paragraph", content: [] }],
          };
        });
        nodes.push({ type: listType, content: items });
        break;
      }
      case "blockquote": {
        const t = token as Tokens.Blockquote;
        const content = t.tokens ? blockTokensToTiptap(t.tokens) : [];
        nodes.push({
          type: "blockquote",
          content:
            content.length > 0
              ? content
              : [{ type: "paragraph", content: [] }],
        });
        break;
      }
      case "space": {
        // Skip whitespace-only tokens
        break;
      }
      case "html": {
        // Strip HTML comments, ignore other HTML
        break;
      }
      default: {
        // Fallback: try to render as paragraph
        if ("text" in token && typeof token.text === "string" && token.text.trim()) {
          nodes.push({
            type: "paragraph",
            content: [{ type: "text", text: token.text }],
          });
        }
        break;
      }
    }
  }

  return nodes;
}

function markdownToTiptap(markdown: string): TiptapDoc {
  const tokens = Lexer.lex(markdown);
  const content = [
    ...INTRO_PARAGRAPHS,
    ...blockTokensToTiptap(tokens),
    ...FOOTER_NODES,
  ] as TiptapBlockNode[];

  return {
    type: "doc",
    attrs: { schemaVersion: "v1" },
    content,
  };
}

// ---------------------------------------------------------------------------
// Substack API client
// ---------------------------------------------------------------------------

async function substackRequest<T>(
  publicationUrl: string,
  path: string,
  token: string,
  options: RequestInit = {}
): Promise<T> {
  const baseUrl = publicationUrl.replace(/\/$/, "");
  const url = `${baseUrl}${path}`;

  const response = await fetch(url, {
    ...options,
    headers: {
      Cookie: `substack.sid=${token}`,
      "Content-Type": "application/json",
      ...((options.headers as Record<string, string>) ?? {}),
    },
  });

  if (!response.ok) {
    const body = await response.text().catch(() => "(no body)");
    throw new Error(
      `Substack API error ${response.status} ${response.statusText}: ${body.slice(0, 500)}`
    );
  }

  return response.json() as Promise<T>;
}

interface SubstackUser {
  id: number;
  name: string;
  email: string;
}

async function getUserId(
  publicationUrl: string,
  token: string
): Promise<number> {
  const user = await substackRequest<SubstackUser>(
    "https://substack.com",
    "/api/v1/reader/me",
    token
  );
  return user.id;
}

interface SubstackDraft {
  id: number;
  title: string;
  draft_title: string;
  slug: string;
  audience: string;
  type: string;
}

async function createDraft(
  publicationUrl: string,
  token: string,
  title: string,
  subtitle: string,
  body: TiptapDoc,
  userId: number
): Promise<SubstackDraft> {
  const draftPayload = {
    draft_title: title,
    draft_subtitle: subtitle,
    draft_body: JSON.stringify(body),
    draft_bylines: [{ id: userId, is_guest: false }],
    audience: "everyone",
    type: "newsletter",
  };

  return substackRequest<SubstackDraft>(
    publicationUrl,
    "/api/v1/drafts",
    token,
    {
      method: "POST",
      body: JSON.stringify(draftPayload),
    }
  );
}

// ---------------------------------------------------------------------------
// Draft file discovery
// ---------------------------------------------------------------------------

function findLatestDraft(overridePath?: string): string {
  if (overridePath) {
    const content = readFileSync(overridePath, "utf-8");
    if (!content.trim()) {
      throw new Error(`Draft file is empty: ${overridePath}`);
    }
    return content;
  }

  let files: { path: string; mtime: number }[];
  try {
    files = readdirSync(DRAFTS_DIR)
      .filter((f) => f.endsWith(".md"))
      .map((f) => {
        const full = join(DRAFTS_DIR, f);
        return { path: full, mtime: statSync(full).mtimeMs };
      })
      .sort((a, b) => b.mtime - a.mtime);
  } catch {
    throw new Error(
      `No drafts directory found at ${DRAFTS_DIR}. Run scripts/analyze_meeting.py first.`
    );
  }

  if (files.length === 0) {
    throw new Error(
      "No markdown drafts found in data/drafts/. Run scripts/analyze_meeting.py first."
    );
  }

  console.log(`Found draft: ${files[0].path}`);
  return readFileSync(files[0].path, "utf-8");
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

async function main() {
  // Parse args
  const args = process.argv.slice(2);
  const fileIdx = args.indexOf("--file");
  const filePath = fileIdx !== -1 ? args[fileIdx + 1] : undefined;
  const dryRun = args.includes("--dry-run");
  const helpFlag = args.includes("--help") || args.includes("-h");

  if (helpFlag) {
    console.log(`Board Watch — Publish draft to Substack

Usage: npx tsx scripts/publish_to_substack.ts [options]

Options:
  --file <path>   Path to a markdown draft (default: most recent in data/drafts/)
  --dry-run       Parse and convert the draft without calling Substack API
  --help, -h      Show this help message`);
    process.exit(0);
  }

  const token = process.env.SUBSTACK_TOKEN;
  const publicationUrl = process.env.SUBSTACK_PUBLICATION_URL;

  // Read and clean the draft
  const rawContent = findLatestDraft(filePath);
  const mdContent = rawContent.replace(/<!--.*?-->\s*/gs, "");

  // Generate title
  const today = new Date();
  const title = `Lebo Board Watch — ${today.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  })}`;

  // Convert markdown to Tiptap
  console.log("Converting markdown to Substack format...");
  const tiptapBody = markdownToTiptap(mdContent);
  console.log(
    `Converted: ${tiptapBody.content.length} top-level nodes`
  );

  if (dryRun) {
    console.log("\n[DRY RUN] Would create draft:");
    console.log(`  Title: ${title}`);
    console.log(`  Nodes: ${tiptapBody.content.length}`);
    console.log(
      `  Body preview: ${JSON.stringify(tiptapBody).slice(0, 200)}...`
    );
    process.exit(0);
  }

  // Validate env vars
  if (!token || !publicationUrl) {
    console.error(
      "Error: SUBSTACK_TOKEN and SUBSTACK_PUBLICATION_URL must be set."
    );
    console.error(
      "Get your token: browser DevTools → Application → Cookies → substack.com → substack.sid"
    );
    process.exit(1);
  }

  // Get user ID
  console.log("Authenticating with Substack...");
  let userId: number;
  try {
    userId = await getUserId(publicationUrl, token);
    console.log(`Authenticated as user ${userId}`);
  } catch (err) {
    console.error("Authentication failed. Is your SUBSTACK_TOKEN valid?");
    console.error(err);
    process.exit(1);
  }

  // Create draft
  console.log("Creating draft on Substack...");
  try {
    const draft = await createDraft(
      publicationUrl,
      token,
      title,
      "",
      tiptapBody,
      userId
    );

    const draftUrl = `${publicationUrl.replace(/\/$/, "")}/publish/post/${draft.id}`;
    console.log("\n" + "=".repeat(60));
    console.log("Draft created successfully!");
    console.log(`  Title:  ${title}`);
    console.log(`  ID:     ${draft.id}`);
    console.log(`  Edit:   ${draftUrl}`);
    console.log("=".repeat(60));
    console.log("\nOpen the link above to review before publishing.");
  } catch (err) {
    console.error("Failed to create draft:", err);
    process.exit(1);
  }
}

main();
